a = 'love'
love1 = 'kiss'
love2 = 'wedding'
love3 = 'passion'
love4 = 'liking'
love5 = 'devotion'
love6 = 'embrace'
love7 = 'marriage'
love8 = 'fancy'
love9 = 'fall in love'
print(love1, love2, love3, love4, love5, love6, love7, love8, love9)
b = 'religion'
religion1 = 'God'
religion2 = 'belief'
religion3 = 'church'
religion4 = 'islam'
religion5 = 'christianity'
religion6 = 'buddhism'
religion7 = 'creed'
religion8 = 'Jesus'
religion9 = 'Muhammed'
print(religion1, religion2, religion3, religion4, religion5, religion6, religion7, religion8, religion9)
c = 'cosmos'
cosmos1 = 'star'
cosmos2 = 'earth'
cosmos3 = 'universe'
cosmos4 = 'nature'
cosmos5 = 'milky-way'
cosmos6 = 'Mars'
cosmos7 = 'planets'
cosmos8 = 'sun'
cosmos9 = 'Mercury'
print(cosmos1, cosmos2, cosmos3, cosmos4, cosmos5, cosmos6, cosmos7, cosmos8, cosmos9)
d = 'avto'
avto1 = 'Bentley'
avto2 = 'mersedes-Benz'
avto3 = 'BMW'
avto4 = 'porsche'
avto5 = 'toyota'
avto6 = 'subaru'
avto7 = 'saab'
avto8 = 'opel'
avto9 = 'audi'
print(avto1, avto2, avto3, avto4, avto5, avto6, avto7, avto8, avto9)
e = 'nature'
nature1 = 'tree'
nature2 = 'flover'
nature3 = 'sun'
nature4 = 'water'
nature5 = 'human'
nature6 = 'mountain'
nature7 = 'earth'
nature8 = 'moon'
nature9 = 'day'
print(nature1, nature2, nature3, nature4, nature5, nature6, nature7, nature8, nature9)

